apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: timezone-config
      mountPath: /etc/localtime
    - name: timezone
      mountPath: /etc/timezone
      subPath: timezone
  volumes:
    - name: timezone-config
      hostPath:
        path: /usr/share/zoneinfo/Asia/Kolkata
    - name: timezone
      configMap:
        name: timezone
